### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by GuoXinrong** [TranSMS/M2TS#1]
hello @TranSMS;
when I run the command to **getAst** for three datasets  and **python run.py** command to train the model according to your project's readme,I met some problems.I can't find some files among your project,and it also report an error：

![D4S89QPJMIZT2)GIO6 LT%9](https://user-images.githubusercontent.com/41418654/165902502-608a2160-2578-4bd0-84d5-914e7a697237.png)

**Comment by wjl311** [comment]
@GuoXinrong Hello, I also encountered this problem, may I ask whether you solved it finally.
