### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by GuoXinrong** [TranSMS/M2TS#2]
hello @TranSMS,
I also find you have files under the **data folder** ,do these files refer to the three datasets? and I don't quite understand what these documents means for their ununiform suffix name and different naming methods.And I can't find The code for handling these files either .In addition ,I also notice that **Java Leclair** folder only has **test** folder.
or maybe I missed some parts
Looking forward to your reply.

**Comment by TranSMS** [comment]
Thank you for your question, we will continue to perfect our code and data folder.
